import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

def setup_custom_fields():
    custom_fields = {
        "Customer": [
            {
                "fieldname": "credit_days_allowed",
                "label": "Credit Days Allowed",
                "fieldtype": "Int",
                "default": "60",
                "insert_after": "credit_limits",
                "description": "Maximum allowed unpaid invoice credit days before account locking."
            },
            {
                "fieldname": "is_account_locked",
                "label": "Account Locked",
                "fieldtype": "Check",
                "read_only": 1,
                "insert_after": "credit_days_allowed",
                "description": "Automatically set if unpaid invoices exceed credit days."
            },
            {
                "fieldname": "lock_reason",
                "label": "Lock Reason",
                "fieldtype": "Small Text",
                "read_only": 1,
                "insert_after": "is_account_locked"
            }
        ],
        "Sales Order": [
            {
                "fieldname": "placed_by_salesman",
                "label": "Placed By Salesman",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "customer",
                "description": "Set to 1 if order was generated by a salesman requiring customer portal approval."
            },
            {
                "fieldname": "customer_approval_status",
                "label": "Customer Approval Status",
                "fieldtype": "Select",
                "options": "Not Required\nPending\nApproved\nRejected",
                "default": "Not Required",
                "insert_after": "placed_by_salesman",
                "description": "Workflow state for Customer approval on Customer Portal."
            },
            {
                "fieldname": "requires_advance_payment",
                "label": "Requires Advance Payment",
                "fieldtype": "Check",
                "read_only": 1,
                "insert_after": "customer_approval_status",
                "description": "Checked automatically if customer has no credit limit issued."
            },
        ],
        "Sales Invoice": [
            {
                "fieldname": "approved_during_lock",
                "label": "Approved Invoicing During Account Lock",
                "fieldtype": "Check",
                "insert_after": "due_date",
                "description": "Allowed for Finance Manager / Director to authorize invoicing for locked accounts."
            }
        ]
    }
    
    create_custom_fields(custom_fields, ignore_validate=True)
    setup_customer_portal_permissions()
    sync_portal_web_forms()
    frappe.db.commit()
    frappe.clear_cache()

def sync_portal_web_forms():
    """
    Ensure portal web forms use has_website_permission hooks instead of
    standard document permissions. When apply_document_permissions=1, Frappe
    bypasses has_website_permission hooks and only checks role-based DocPerms,
    which causes 403 for Customer portal users who rely on those hooks.
    """
    web_forms = ["customer-order", "customer-pending-approvals", "customer-invoice"]
    for wf_name in web_forms:
        if frappe.db.exists("Web Form", wf_name):
            try:
                current = frappe.db.get_value("Web Form", wf_name, "apply_document_permissions")
                if current:
                    frappe.db.set_value("Web Form", wf_name, "apply_document_permissions", 0)
            except Exception as e:
                frappe.log_error(f"Error updating web form {wf_name}: {e}")

def setup_customer_portal_permissions():
    """
    Grants essential read permissions to Customer role for Portal Web Forms.
    """
    doctypes = ["Account", "Customer", "Sales Order", "Sales Invoice", "Customer Support Request", "Customer Ledger", "GL Entry", "Item"]
    for dt in doctypes:
        if frappe.db.exists("DocType", dt):
            if not frappe.db.exists("Custom DocPerm", {"parent": dt, "role": "Customer"}):
                try:
                    docperm = frappe.new_doc("Custom DocPerm")
                    docperm.parent = dt
                    docperm.parenttype = "DocType"
                    docperm.parentfield = "permissions"
                    docperm.role = "Customer"
                    docperm.read = 1
                    docperm.export = 1
                    docperm.insert(ignore_permissions=True)
                except Exception as e:
                    frappe.log_error(f"Error adding Customer permission for {dt}: {e}")
